modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="logo.png"
displayURL="https://github.com/Ccat-Q/No-more-Admin-AE2-Network-Analyser"
issueTrackerURL="https://github.com/Ccat-Q/No-more-Admin-AE2-Network-Analyser/issues"
description='''${mod_description}'''

[[mixins]]
config="no_more_admin_ae2.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2netanalyser"
type="required"
versionRange="[1.21-2.1.5-neoforge]"
ordering="AFTER"
side="BOTH"
